### ISSUE TITLE
referencias

### ISSUE THREAD

**Issue by cmzambranat** [hugocalcad/curso_r_espacial#1]
- [x] Crear bibliografia en formato bibtex (puedes usar [Zotero](https://www.zotero.org/download/))
- [x] Se puede insertar referencias usando el paquete [`citr`](https://github.com/crsh/citr)

**Comment by hugocalcad** [comment]
Agregue bibliografia, estoy utilizando zotero para exportar a los archivos .bib y estoy usando citr para agregar las citas a los archivos rmd

**Comment by cmzambranat** [comment]
completado en merge https://github.com/hugocalcad/curso_r_espacial/commit/cbb051e391a64f50200ba4096f1a024419d63898
(tengo q aprender como referencias merges in GitHub)
